name: Python CI with Ruff Linter

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Python Tests
        run: |
          pytest --cov=code_wise --cov-report=term-missing

  lint:
    runs-on: ubuntu-latest
    needs: test  # This ensures the lint job runs after the test job

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Ruff
        run: |
          python -m pip install --upgrade pip
          pip install ruff  # Install the Ruff linter

      - name: Run Ruff Linter
        run: |
          ruff check . --fix  # Run Ruff to lint and automatically fix any issues
